dist: trusty
language: java
jdk:
  - oraclejdk8
python:
  - "3.6"

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
- ./gradlew -x test clean bootjar

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

after_success:
- mkdir deploy && cp build/libs/*.jar deploy/

before_deploy:
  - openssl aes-256-cbc -K $encrypted_96cca6b14f03_key -iv $encrypted_96cca6b14f03_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install qiniu
  - wget https://raw.githubusercontent.com/dongfg/python-script/master/qiniu_rsync.py
deploy:
- provider: script
  skip_cleanup: true
  script: QINIU_AK=${QINIU_AK} QINIU_SK=${QINIU_SK} python3 qiniu_rsync.py dongfg deploy/
- provider: script
  skip_cleanup: true
  script: ssh -o StrictHostKeyChecking=no -i deploy_key -p ${DEPLOY_PORT} ${DEPLOY_USER}@${DEPLOY_HOST} '${PUBLISH_SCRIPT}'