language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_96cca6b14f03_key -iv $encrypted_96cca6b14f03_iv -in deploy_key.enc -out deploy_key -d
after_success:
- chmod 600 deploy_key
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -avzrtopg --delete -e 'ssh -o StrictHostKeyChecking=no -i deploy_key -p ${DEPLOY_PORT}' target/*.jar ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}