server:
  port: 20000
spring:
  profiles:
    include: external
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: apidb
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Zk985D4gn!2h