spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  jpa:
    open-in-view: false
management:
  endpoint:
    health:
      show-details: when_authorized
server:
  servlet:
    session:
      timeout: 10h