server:
  port: 20000
spring:
  profiles:
    include: external
  data:
    mongodb:
      uri: mongodb://apidb:123456@dev.dongfg.com/apidb
  datasource:
    url: jdbc:mysql://dev.dongfg.com:3306/api?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mmDfg@123456