spring:
  application:
      name: dongfg-api
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  jpa:
    open-in-view: false
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      cors:
        allow-credentials: true
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"