server:
  port: 20000
spring:
  data:
    mongodb:
      host: 10.64.90.5
      port: 27017
      database: apidb
  datasource:
    url: jdbc:mysql://127.0.0.1/api?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: changeit
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: springBootHikariPool
      maximum-pool-size: 10