graphql:
  servlet:
    mapping: /graphql
fastjson:
  charset: UTF-8
  date-format: yyyy-MM-dd HH:mm:ss
  serializer-features:
    - writedateusedateformat
spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  security:
    user:
      name: admin
      password: admin@123
  jpa:
    open-in-view: false