graphql:
  servlet:
    mapping: /graphql
fastjson:
  charset: UTF-8
  date-format: yyyy-MM-dd HH:mm:ss
  serializer-features:
    - writedateusedateformat
security:
  user:
    name: ENC(9H4p5VFHTgTbtyVfB0o0QA==)
    password: ENC(MRBzREiLxWPJJrGo96ZjuooM6HeM8SgR)