graphql:
  servlet:
    mapping: /graphql
fastjson:
  charset: UTF-8
  date-format: yyyy-MM-dd HH:mm:ss
  serializer-features:
    - writedateusedateformat
security:
  user:
    name: admin
    password: admin@123