management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      cors:
        allow-credentials: true
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"