server:
  port: 20000
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: apidb
      username: apidb
      password: ENC(FpBxTMBgdWavOXrPs7tl+7/kUUJvdvO8)
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ENC(kWYJI+O0UuB1IrhrP70Jrg==)
    password: ENC(AmqfJS8ShSIkPkhXghh7IgGkm1VxH0aC)
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: springBootHikariPool
      maximum-pool-size: 10